### ISSUE TITLE
建议再加个“去逛逛”

### ISSUE THREAD

**Issue by Ehustein** [HairDesappear/2020-618-TB-miaobi-autojs#1]
建议再加个“去逛逛”

**Comment by Ehustein** [comment]
另外“去浏览”有些问题，因为存在去浏览完做完别的任务之后再出现的情况，不应该去判断完成去浏览任务，应该是只要有去浏览，就去点

**Comment by oops-fanglin** [comment]
hello~抱歉这么迟才回复，这两天我也一直在想这个问题
1.对于第一个的“去逛逛”的问题，有一个聚划算的浏览任务倒是还好，但是淘宝人生的任务就会让脚本卡住
2.第二个的“去浏览“问题，今天提交了解决方案，就是把将关键词装成数组，每次完成一个就遍历判断页面是否还存在任一关键字，这样就应该可以避免每个关键字只判断一次的问题了
`function justDoIt(keywords){
    var messionCount = 0;
        while(containsKeywords(keywords)){
            switch(keywords[i]){
                case "签到" :
                case "去兑换" :
                case "去观看":missionClick(keywords[i]);
                    break;
                case "去完成":
                case "去逛逛":
                case "去搜索":
                case "去浏览":mission15s(keywords[i]);
                    break;
            }
}`
大概是这样，奈何我的能力比较有限，本来想着把农场和淘宝人生做做，但是想了想，又好像有点南和复杂

**Comment by Ehustein** [comment]
观察了好长时间：

5.2版本的进入方式有些奇怪，搜索进入的话又有当打开支付宝在首页的时候才有效
建议：如果保留搜索进入则在检测不到活动页面的时候连续返回直到退出再尝试重进，
当然我觉得还是原来直接链接打开的方式好
（如果是为了避免重复打开活动也可以在打开淘宝之后检测不是主页的话就返回退出重进）
其实还是复杂，我觉得重复打开并不影响，保留原来的就好

5.2版本不知道是我的其他任务中途打断本脚本还是什么原因好像总是会中途断掉

另外建议再增加个`“去参与”`不然9点以后运行会有一些任务被组队任务挡掉

`“去浏览”`的问题由于本人不会代码，但是我想可以简单的在运行完所有任务之后再加个执行去浏览的函数应该能解决问题，再不行跑两遍，简单粗暴

还有个问题是去首页浏览的问题总是到主页之后活动页又丢了导致无法继续完成任务，所以在遍历判断页面之前还需要加个判断前提是否在活动页再去判断，不在的话就去打开活动页，很多意外中断也会遇到这个问题

活动快结束了，感觉做到完美也是很难，能力有限我仅能提供我自己的想法和思路，祝玩得开心！

**Comment by Ehustein** [comment]
刚才阅读代码发现你已经加了这段代码：
```
    // 防止主页浏览任务中止脚本
    if(text("做任务，领喵币").find().empty()){
        openActivityPage();
        openTaskList();
```
那么很简单其实就是`openActivityPage()`的问题，把这个函数换成4.1版本的打开活动方式应该就比较完美不会再意外打断了，而且由于这段代码中脚本不会去打开淘宝也不会和其它运行中的脚本打架

**Comment by Ehustein** [comment]
真是惨，任务改来改去，有一天晚上还出现了列车降价的bug，做完所有任务最后还是卡在57级，红包也只有十几元，本次活动我给淘宝差评
